### ISSUE TITLE
Problem with Fa

### ISSUE THREAD

**Issue by whrEngr** [manrajsingh/seismic-maps#24]
for 1070 Primio Way, Sparks NV
Risk Cat 2
Site class - D-default
Fa is given as Fa=2,
However Fa should be 1.2.

AITC site correctly gives Fa=1.2

**Comment by AliSumer-Git** [comment]
Hi,

I am unable to replicate the issue you mentioned, but I am getting 1.2 (not 2). 
ASCE 7-16
Risk Cat 2
D-default
1070 Primio Way, Sparks Nevada
I am getting Fa=1.2. Could you give me a more detailed run info? 
Thanks,

Ali
seismicmaps.org

**Comment by whrEngr** [comment]
Ali,
Well I can’t duplicate.  I must have had something wrong.
Thanks for your quick response and sorry, must be my mistake

Wayne H. Reid, SE
490 Hot Springs Rd.
Carson City, NV  89706
775.230.2747

**Comment by manrajsingh** [comment]
Closing this issue since @whrEngr can't replicate it. If you ever come across it again, please take a screen shot of parameters and output.
