### ISSUE TITLE
gridSpacing undefined

### ISSUE THREAD

**Issue by cnealey** [manrajsingh/seismic-maps#25]
I'm receiving error message - 
     USGS service returned the following error
     500 Internal Server Error
     Cannot read property 'gridSpacing' of undefined
This occurs regardless of location.  I'm using internet explorer.

Please advise.
Thanks

-Clint Nealey, EIT-
PBS

**Comment by mhe-Mason** [comment]
Same issue.
Did several test locations, all of them come back with the same error.

Tried other websites that generate seismic data, they also returned this error.

R. Mason
M-H-E

**Comment by woodarch** [comment]
Also receiving same error and also tried other websites and received same error. 

USGS service returned the following error
500 error
Cannot read property 'gridSpacing' of undefined

**Comment by AliSumer-Git** [comment]
Currently USGS servers are down. We have contacted USGS team about this issue. 
Thanks for your feedback,

Ali 
Seismicmaps.org

**Comment by AliSumer-Git** [comment]
USGS servers are online again. Issue is resolved. Please make sure to clear browser cache to not get the same error message. 
Ali
Seismicmaps.org

**Comment by woodarch** [comment]
Thanks Ali, it is working for me again. Much appreciated.

**Comment by manrajsingh** [comment]
USGS has fixed the problem with their services.

**Comment by Sammed46** [comment]
Please today at 14/2/2023
Also receiving same error and also tried other websites and received same error.

USGS service returned the following error
500 error
Cannot read property 'gridSpacing' of undefined
