### ISSUE TITLE
Seismic Design Category

### ISSUE THREAD

**Issue by paisiello** [manrajsingh/seismic-maps#26]
When using Site Class D it gives "See Section 11.4.8" for Fv, SM1, SD1, and the Seismic Design Category. Section 11.4.8 requires a site-specific ground motion analysis for Site Class E and Site Class D when S1>=0.2.

However, there are exceptions given where a site-specific ground motion analysis is NOT required. For people who wish to use these exceptions and want to determine the Seismic Design Category, would you consider modifying your web page so that it gives the Fv, SM1, SD1, and the Seismic Design Category values with an added comment in the description?

For example:

Site Class = D
Fv = 2.2          assumes exception in Section 11.4.8 applies
SM1 = 0.44    assumes exception in Section 11.4.8 applies
SD1 = 0.293   assumes exception in Section 11.4.8 applies
SDC = D         assumes exception in Section 11.4.8 applies

**Comment by AliSumer-Git** [comment]
Sorry for the very late reply. Your question points out a valid concern for the upcoming code. I am considering to add a note, however, I am afraid to cause more confusion about ASCE 7-16. Not decided yet. 

Thanks,

Ali

**Comment by StantonKV** [comment]
I have run into this issue too and would like to add that it is still a problem when using ASCE 7-10. This behavior limits the usefulness of results returned for many sites in the bay area and is confusing analysts across the region. I strongly encourage adding a note to clarify the reason for the behavior.

**Comment by manrajsingh** [comment]
@AliSumer-Git  is this going to be a feature request or are we still deferring this?

**Comment by manrajsingh** [comment]
never mind .. the UI was updated to reflect "See Section 11.4.8" in such scenarios
