### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by Geoeng5755** [manrajsingh/seismic-maps#28]
The map only loads for a second, then I get this message: "This page didn't load Google Maps correctly. See the JavaScript console for technical details."

Also, the program doesn't work when I enter an address.  I use this program on a regular basis so this is definitely something new.

**Comment by WishAllVA** [comment]
I have worked with maps in JavaScript. I can do that

**Comment by manrajsingh** [comment]
@Geoeng5755  did you fork the repository and tried to use it for yourself? or are you having an issue on https://seismicmaps.org ?
