### ISSUE TITLE
need to add exception option for 11.4.8 to get ALL the design parameters

### ISSUE THREAD

**Issue by kathycage** [manrajsingh/seismic-maps#30]
your software should have an option for using the exceptions in ASCE 7-16 11.4.8 so that all the design parameters are calculated.  Only a handful of places will NOT meet one of the exceptions.  The usefulness of using software as a time saver over doing hand calcs is limited when I have to do hand calcs to get 4 different parameters that the IBC & CBC require to be on plans, i.e.: SM1, SD1, Fv & SDC.

**Please** add an option for employing one of the 11.4.8 Exceptions that will allow all the design parameters to be calculated for the printout.

**Comment by manrajsingh** [comment]
@AliSumer-Git  thoughts ?

**Comment by manrajsingh** [comment]
UI reflects "See Section 11.4.8" in such scenarios
