### ISSUE TITLE
null returns

### ISSUE THREAD

**Issue by ddcpe** [manrajsingh/seismic-maps#31]
Get a null value return for Sm1, Sd1, Sdc, Fv.  Input a valid address (returns Lat 38.4577202, Long -122.7615176).  Refernce = ASCE 7-16, Risk Cat = II, Site Class = D.
Any idea why it doesn't return a value?

**Comment by manrajsingh** [comment]
we had updated the UI to refer to section 11.4.8 in such scenarios
