### ISSUE TITLE
Seismic Design Maps Not Working

### ISSUE THREAD

**Issue by secondspassed** [manrajsingh/seismic-maps#34]
On multiple devices and multiple networks, browsers and target locations, seismicmaps.org says something is wrong with google maps and the tool refuses to return results for a location. The message is “Oops! Something went wrong. This page didn’t load Google maps correctly. See the JavaScript console for technical details.” My company relies on this site for fire sprinkler sway brace design and the information is crucial. Is there another similar site available if this one will not be working for some time?

**Comment by AliSumer-Git** [comment]
Thanks for bringing this to our attention. We fixed the issue yesterday.

**Comment by DenisePoeltler** [comment]
Yes.  Thanks for fixing it.


-----Original Message-----

**Comment by SantiAEDDS** [comment]
Im having the same problem, I input the data, and i click on go, and nothing happens.

**Comment by manrajsingh** [comment]
This issue was resolved
