### ISSUE TITLE
Sx1 value for ASCE41-13

### ISSUE THREAD

**Issue by dleechuy** [manrajsingh/seismic-maps#37]
I am finding that the Sx1 value of the BSE-1E earthquake is calculated using a different Fv value from what is printed. Can you verify that it is pulling the same Fv value from the one in the printed report?

thanks,

![ASCE41-13 bse-1e](https://user-images.githubusercontent.com/70072629/90963301-78b27a00-e484-11ea-9042-3f14c9968169.JPG)

**Comment by manrajsingh** [comment]
@AliSumer-Git can you verify this please

**Comment by AliSumer-Git** [comment]
The values appear correct. Please keep in mind the accuracy is in third digit (1/1000 g) . When you multiply a third digit (rounded number), you can get a sligthly different number in the third digit. 


0.026 x 2.4 =~ 0.061
