### ISSUE TITLE
Values not coming up in Chrome or Firefox

### ISSUE THREAD

**Issue by ghost** [manrajsingh/seismic-maps#38]
After clicking selecting parameters, entering the address, and clicking Go, the map updates to the correct location and the Go button says "Searching..." and the spinning stopwatch shows up, but the results never appear.

Same behavior on Chrome and Firefox.

**Comment by OnguardGroup** [comment]
> After clicking selecting parameters, entering the address, and clicking Go, the map updates to the correct location and the Go button says "Searching..." and the spinning stopwatch shows up, but the results never appear.
> 
> Same behavior on Chrome and Firefox.

I am experiencing same problem in Chrome or Edge. Main function of website is non-operational

**Comment by ghost** [comment]
Seems to be working now...

**Comment by spakwa** [comment]
I'm getting the same issue in Chrome.  That stopwatch just keeps spinning...

**Comment by spakwa** [comment]
It seems to be working again now.

**Comment by MattBSE** [comment]
I'm getting the same issue in all browsers, the stopwatch keeps spinning. Has been happening since at least December 18th...

**Comment by manrajsingh** [comment]
There was an issue with USGS service and has since been resolved.
