### ISSUE TITLE
Error Reporting Seismic Hazard Data

### ISSUE THREAD

**Issue by LeslieScott-TIC** [manrajsingh/seismic-maps#39]
GPS coords:  24.57540277, -81.68932393
returns error message

USGS service returned the following error
500 error
Cannot read property 'sauh' of undefined

Is hazard data available for this locatoin?

**Comment by manrajsingh** [comment]
@AliSumer-Git  does this mean that USGS does not have hazard data available for this location?

**Comment by AliSumer-Git** [comment]
Islands or pretty much anything offshore is outside of USGS provided map.
