### ISSUE TITLE
Calculation never stops 

### ISSUE THREAD

**Issue by coriar** [manrajsingh/seismic-maps#42]
after entering design information, the clock continues non-stop. I never get an answer. It worked well last week
![image](https://user-images.githubusercontent.com/86388721/123186183-7b874e00-d44c-11eb-9caa-d2a7ee4b10e0.png)

**Comment by manrajsingh** [comment]
I believe USGS's servers might have had some issue around that time. I just ran this with the same parameters and it worked just fine. Please let me know if you are still having this issue.
