### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by emosfet** [manrajsingh/seismic-maps#43]
Geocode was not successful for the following reason:
ERROR

**Comment by manrajsingh** [comment]
Could you give me more details as to what where you trying to search ?

**Comment by emosfet** [comment]
Manraj

Thanks for reaching out.
The site is working fine on Microsoft Edge browser, but return error on
google chrome browser.

Regards

Chris Lu

**Comment by msingh-oshpd** [comment]
If you can give more details as to what issues you are experiencing with google chrome, feel free to reopen this issue.
