### ISSUE TITLE
Pass Lat Long or Address?

### ISSUE THREAD

**Issue by andrewteg** [manrajsingh/seismic-maps#44]
Is it possible to pass in the lat long or an address for easy linking from another application?  For example I'd like to just link to https://seismicmaps.org/?lat=37.5612807&lng=-78.30430869999999 or even https://seismicmaps.org/?address=123%20Main%20St and the Reference, Risk Category, and Site Class for convenience to build a list of URLs from a list of lat/long or addresses.

Is this possible?
Thanks!

**Comment by manrajsingh** [comment]
You can pass the address as URL parameters

Try the following URL in your browser

https://seismicmaps.org/?location=2020+west-el+camino+ave+sacramento+ca&ref=asce7-10&risk-category=i&site-class=A&title=Your+Project+Title
or 
https://seismicmaps.org/?location=38.61206410,-121.50836650&ref=asce7-10&risk-category=i&site-class=A&title=Your+Project+Title

location=2020+west-el+camino+ave+sacramento+ca
        or
location=38.61206410,-121.50836650
ref=asce7-10
risk-category=i
site-class=A
title=Your+Project+Title

**Comment by andrewteg** [comment]
Thanks.

As an FYI, I tried https://seismicmaps.org/?location=2020+west-el+camino+ave+sacramento+ca&ref=asce7-10&risk-category=i&site-class=D&title=Your+Project+Title and that gave me site class of **D - Stiff Soil**, but doing https://seismicmaps.org/?location=2020+west-el+camino+ave+sacramento+ca&ref=asce7-10&risk-category=i&site-class=D-default&title=Your+Project+Title did not give me site class of **D - Default** as expected.  I'm not sure if I just have the wrong site-class but that seems to be the value in the select.
