### ISSUE TITLE
ASCE 41-17 Query Error

### ISSUE THREAD

**Issue by glenn-rix** [manrajsingh/seismic-maps#45]
When querying to obtain ground motion parameters for ASCE 41-17, I receive the following error:

USGS service returned the following error
500 Internal Server Error
AFE Value (0.004462871026284194) must be within the range: 0.0043833 and 0

If I specify a "Custom Probability" of 0.02, it works fine, but I want all of the default hazard levels.

Glenn J. Rix

**Comment by msingh-oshpd** [comment]
@AliSumer-Git can you respond to this please

**Comment by AliSumer-Git** [comment]
Looks like everything is working as it should. Recently USGS servers were timing out. Try the same search twice consecutively and see if the delay in USGS servers is the issue. 
Ali

> When querying to obtain ground motion parameters for ASCE 41-17, I receive the following error:
> 
> 
> 
> USGS service returned the following error
> 
> 500 Internal Server Error
> 
> AFE Value (0.004462871026284194) must be within the range: 0.0043833 and 0
> 
> 
> 
> If I specify a "Custom Probability" of 0.02, it works fine, but I want all of the default hazard levels.
> 
> 
> 
> Glenn J. Rix
