### ISSUE TITLE
Reques for information

### ISSUE THREAD

**Issue by Kamalhussain770** [manrajsingh/seismic-maps#48]
Hi Sir,

Actually im looking for seismic design parameter based on ASCE 7-16 for the Rwanda (east african country) but when im using this website for such purpose, it showing me "Error" and not going to work. i tried to use microsoft edge also for this but still the same error is showing.

Regards

Kamal Hussain
Email ID = kamal.uetian@gmail.com

**Comment by msingh-oshpd** [comment]
Hi Kamal,

This application pulls data from USGS and they do not have data on any other country.
