### ISSUE TITLE
This page can't load Google Maps correctly.

### ISSUE THREAD

**Issue by nelserik** [manrajsingh/seismic-maps#49]
Before entering address, a google textbox displayed "This page can't load Google Maps correctly."  When I entered an address, this prompt came up: "Geocode was not successful for the following reason: REQUEST_DENIED".  I am using a Google Chrome browser.

**Comment by manrajsingh** [comment]
We had an issue with geocoding and it has been resolved.

**Comment by nelserik** [comment]
Thanks.
