### ISSUE TITLE
Hazard Map Tool won't "GO"

### ISSUE THREAD

**Issue by ChristiK-GSI** [manrajsingh/seismic-maps#51]
The "Site Class" drop down menu is empty and the tool doesn't work when "GO" is clicked. Please help!

**Comment by manrajsingh** [comment]
Which browser are you using? 
Have you tried using Google Chrome / Chromium / Firefox / Safari ?

**Comment by ChristiK-GSI** [comment]
Hello,
I am and have been using Google Chrome.
I downloaded and tried each of the alternative browsers you suggested and ended up with the same result.
Please advise, thank you.

Thank you,
***@***.***<https://guardiansouthinc.com/>

CHRISTI KOCHEMS
Fire Sprinkler Design Technician
Contractors Lic. C-16 734574
[icon]
(310) 327-2827<tel:(310)%20327-2827>
[icon]
(951) 445-3728<tel:(951)%20445-3728>
[icon]
***@***.******@***.***​>
[icon]
www.guardiansouthinc.com<https://guardiansouthinc.com/>
[icon]
1441 Main St #260, Ramona, CA 92065
This transmission is intended only for use by the intended recipient(s). If you are not an intended recipient you should not read, disclose, copy, circulate or in any other way use the information contained in this transmission. The information contained in this transmission may be confidential and/or privileged. If you have received this transmission in error, please notify the sender immediately and delete this Transmission including any attachments.

**Comment by manrajsingh** [comment]
Stale issue
