### ISSUE TITLE
Map information will not display 

### ISSUE THREAD

**Issue by angsos** [manrajsingh/seismic-maps#54]
Input the information and the website is say access denied.

**Comment by cdigregb1** [comment]
I am also having an issue, using the latest version of Chrome. When I first open the page it says it can't load Google Maps correctly.

If I click OK on the error and try to proceed, when I click GO I get the following error:
Geocode was not successful for the following reason:
REQUEST_DENIED

![image](https://user-images.githubusercontent.com/122484378/211903331-00b9e3ee-2546-4849-bb29-547dfc0116c9.png)
![image](https://user-images.githubusercontent.com/122484378/211903847-9a19a421-54e3-47bb-ba64-7ba4af9bfde1.png)

**Comment by LukeDaur** [comment]
Same issue as SDIGregb1

**Comment by cdigregb1** [comment]
I just tried the site again. I no longer get the first error, but if I try to search by address, I still get the Geocode request denied error.

If I click a location on the map, which loads coordinates and then click GO, there is no error.

**Comment by manrajsingh** [comment]
We had issues with our Google account .. this was fixed.
