### ISSUE TITLE
Service Error (500)

### ISSUE THREAD

**Issue by jdf8tc** [manrajsingh/seismic-maps#55]
Around Denver, CO, I'm getting timeout and service errors (0 and 500 errors). Is there a way I can get this datasheet manually? Let me know as soon as you can.  Thank you.

**Comment by manrajsingh** [comment]
Do you have a specific address / coordinates for which you're getting the errors? 

The data is pulled based on location directly from USGS servers; so we do not have a datasheet to provide.

**Comment by jdf8tc** [comment]
Thank you for your assistance. This error is now cleared around Denver. It must have been an outage. Have a good day.
