### ISSUE TITLE
USGS Service Error: (Error 500)

### ISSUE THREAD

**Issue by irpkyson** [manrajsingh/seismic-maps#58]
For the last 3 days I have been running into this error. Is there a solution coming or a way to get it up and running again. I have many projects that require the use of this tool.
@manrajsingh 
![Screenshot 2023-08-07 072445](https://github.com/manrajsingh/seismic-maps/assets/141645162/7ba9a92d-2dd5-4d92-bf4b-945274cfb9cf)

**Comment by manrajsingh** [comment]
USGS web services were down for some period of time and as a result this tool wasn't operational, resulting in timeout error. USGS web services are now operational so this tool should work as expected.

I also tested it with the parameters in the screenshot. It seems to be working now.
